server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
      - id: api_route
        uri: http://8.140.60.185:8181
        predicates:
          - Path=/api/**
dubbo:
  application:
    name: xunlian_gateway
#    qos-enable: true
#    qos-accept-foreign-ip: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: gateway
    address: nacos://8.140.60.185:8848
#  config-center:
#    timeout: 40000


